//Ficher qui va servir à l'importation de donnée des NOTAMS sur le site de la FAA
export default data = [
    {
        id:'160604',
        title:`{CYUL ST-ALPHONSE/LAC CLOUTIER(WATER)
        CTC2 AMEND PUB: NEW TOWER 461923N 733958W (APRX 8 NM NNE AD)
        312 FT AGL 1913 MSL LGTD AND PAINTED}`
      },
      {
        id: '182180',
        title: `CYUL MONTREAL/LAVAL(ARTOPEX PLUS)(HELI)
        CLP2 AMEND PUB: HELI DATA TO READ: FATO/TLOF 62 FT DIA
        ASPH/COMPACTED SNOW. SAFETY AREA 83 FT DIA GRASS/COMPACTED SNOW.
        MAX HELI OVERALL LENGTH 41.5 FT
        PRO TO READ: ARR/DEP 248 DEG FR HELI (H3), ARR/DEP CURVED 108 DEG
        TO 061 DEG FR HELI (H3)`,
      },
      {
        id: '190783',
        title: `CYUL MONTREAL/PIERRE ELLIOTT TRUDEAU INTL
        CYUL AMEND PUB: NEW TRANSMISSION LINE FROM 453336N 733852W TO
        453217N 733945W (APRX 6 NM NE CYUL, APRX 1.2 NM NNE CPZ6)
        310 FT AGL 440 MSL NOT LGTD NOT PAINTED.`,
      },
      {
        id: '190900',
        title: `CYUL JOLIETTE/ST-THOMAS
        CJO2 AMEND PUB: OPR TEL TO READ: 450-757-0685`,
      },
      {
        id: '191000',
        title: `CYUL MONTREAL/PIERRE ELLIOTT TRUDEAU INTL
        CYUL WEF 2019 JUN 20 0901 AMEND CAP 5 AND CAP 6: AD CHART:
        PLAN VIEW NOTE: DELETE: THR 24R DISPLACED 3332 FT`,
      },
      {
        id: '191003',
        title: `CYUL MONTREAL/PIERRE ELLIOTT TRUDEAU INTL
        CYUL WEF 2019 JUN 20 0901 AMEND PUB: RNAV (GNSS) RWY 06L APCH:
        PLAN VIEW: GOVAG: FLYBY WPT INSTEAD OF FLYOVER WPT`,
      },
      {
        id: '191072',
        title: `CYUL MONTREAL/PIERRE ELLIOTT TRUDEAU INTL
        CYUL TWY E CLSD BTN RWY 06L/24R AND TWY B
        1906261300 TIL APRX 1910182359`,
      },
      {
        id: '191073',
        title: `CYUL MONTREAL/PIERRE ELLIOTT TRUDEAU INTL
        CYUL AMEND RNAV(GNSS) RWY 24R APCH:
        PROFILE VIEW: TDZE TO READ: 106`,
      },

]



  
  
 
  
  

